import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(3000),
  API_PREFIX: Joi.string().default('api/v1'),
  MONGODB_URI: Joi.string().required(),
  LOG_LEVEL: Joi.string().default('log'),
  DIAN_ENVIRONMENT: Joi.string().valid('testing', 'production').required(),
  DIAN_PROFILE_EXECUTION_ID: Joi.string().valid('1', '2').required(),
  DIAN_SEND_MODE: Joi.string().valid('sync', 'async').required(),
  DIAN_SOFTWARE_ID: Joi.string().required(),
  DIAN_SOFTWARE_PIN: Joi.string().required(),
  DIAN_WSDL_TEST: Joi.string().uri().required(),
  DIAN_WSDL_PROD: Joi.string().uri().required(),
  DIAN_TEST_SET_ID: Joi.string().allow('').optional(),
  DIAN_COMPANY_NIT: Joi.string().required(),
  DIAN_COMPANY_DV: Joi.string().required(),
  DIAN_COMPANY_NAME: Joi.string().required(),
  DIAN_COMPANY_REGIME: Joi.string().required(),
  DIAN_COMPANY_TAX_LEVEL: Joi.string().required(),
  DIAN_COMPANY_RESPONSIBILITY: Joi.string().required(),
  DIAN_COMPANY_PHONE: Joi.string().required(),
  DIAN_COMPANY_EMAIL: Joi.string().email().required(),
  DIAN_COMPANY_ADDRESS: Joi.string().required(),
  DIAN_COMPANY_CITY_CODE: Joi.string().required(),
  DIAN_COMPANY_CITY_NAME: Joi.string().required(),
  DIAN_COMPANY_DEPARTMENT_CODE: Joi.string().required(),
  DIAN_COMPANY_DEPARTMENT_NAME: Joi.string().required(),
  DIAN_COMPANY_COUNTRY_CODE: Joi.string().required(),
  DIAN_COMPANY_COUNTRY_NAME: Joi.string().required(),
  DIAN_COMPANY_MUNICIPALITY_CODE: Joi.string().required(),
  DIAN_RESOLUTION_NUMBER: Joi.string().required(),
  DIAN_RESOLUTION_PREFIX: Joi.string().required(),
  DIAN_RESOLUTION_FROM: Joi.number().required(),
  DIAN_RESOLUTION_TO: Joi.number().required(),
  DIAN_RESOLUTION_VALID_FROM: Joi.string().isoDate().required(),
  DIAN_RESOLUTION_VALID_TO: Joi.string().isoDate().required(),
  DIAN_TECHNICAL_KEY: Joi.string().required(),
  DIAN_QR_TEST_URL: Joi.string().uri().required(),
  DIAN_QR_PROD_URL: Joi.string().uri().required(),
  CERTIFICATE_PATH: Joi.string().required(),
  CERTIFICATE_PASSPHRASE: Joi.string().allow('').required(),
  MAIL_HOST: Joi.string().required(),
  MAIL_PORT: Joi.number().required(),
  MAIL_SECURE: Joi.string().valid('true', 'false').required(),
  MAIL_USER: Joi.string().required(),
  MAIL_PASS: Joi.string().required(),
  MAIL_FROM: Joi.string().required(),
  PDF_OUTPUT_DIR: Joi.string().required(),
  POS_PRINTER_WIDTH_MM: Joi.number().default(80),
});