import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(3000),
  API_PREFIX: Joi.string().default('api/v1'),
  MONGODB_URI: Joi.string().when('NODE_ENV', {
    is: 'development',
    then: Joi.string().default('mongodb://localhost:27017/morchis-dian'),
    otherwise: Joi.string().required(),
  }),
  LOG_LEVEL: Joi.string().default('log'),
  DIAN_ENVIRONMENT: Joi.string().valid('testing', 'production').required(),
  DIAN_PROFILE_EXECUTION_ID: Joi.string().valid('1', '2').required(),
  DIAN_SEND_MODE: Joi.string().valid('sync', 'async').required(),
  DIAN_SOFTWARE_ID: Joi.string().required(),
  DIAN_SOFTWARE_PIN: Joi.string().required(),
  DIAN_WSDL_TEST: Joi.string().uri().required(),
  DIAN_WSDL_PROD: Joi.string().uri().required(),
  DIAN_SOAP_TIMEOUT_MS: Joi.number().integer().min(1000).default(20000),
  DIAN_SOAP_MAX_RETRIES: Joi.number().integer().min(0).max(10).default(2),
  DIAN_SOAP_RETRY_BASE_MS: Joi.number().integer().min(50).default(400),
  DIAN_SOAP_RETRY_MAX_MS: Joi.number().integer().min(100).default(4000),
  DIAN_WS_SECURITY_ENABLED: Joi.string().valid('true', 'false').default('false'),
  DIAN_WS_SECURITY_USERNAME: Joi.string().allow('').optional(),
  DIAN_WS_SECURITY_PASSWORD: Joi.string().allow('').optional(),
  DIAN_WS_SECURITY_MUST_UNDERSTAND: Joi.string().valid('true', 'false').default('true'),
  DIAN_WS_SECURITY_HAS_TIMESTAMP: Joi.string().valid('true', 'false').default('true'),
  DIAN_WS_SECURITY_HAS_NONCE: Joi.string().valid('true', 'false').default('true'),
  DIAN_ASYNC_RECONCILIATION_ENABLED: Joi.string().valid('true', 'false').default('false'),
  DIAN_ASYNC_RECONCILIATION_INTERVAL_MS: Joi.number().integer().min(5000).default(60000),
  DIAN_ASYNC_RECONCILIATION_BATCH_SIZE: Joi.number().integer().min(1).max(500).default(20),
  DIAN_REPROCESS_ALLOWED_STATUS_CODES: Joi.string().allow('').optional(),
  DIAN_REPROCESS_BLOCKED_STATUS_CODES: Joi.string().allow('').optional(),
  DIAN_REPROCESS_BLOCKED_RULE_PREFIXES: Joi.string().allow('').optional(),
  DIAN_REPROCESS_REQUIRE_APPROVAL_FOR_BLOCKED: Joi.string().valid('true', 'false').default('true'),
  DIAN_TEST_SET_ID: Joi.string().allow('').optional(),
  DIAN_COMPANY_NIT: Joi.string().required(),
  DIAN_COMPANY_DV: Joi.string().required(),
  DIAN_COMPANY_NAME: Joi.string().required(),
  DIAN_COMPANY_REGIME: Joi.string().required(),
  DIAN_COMPANY_TAX_LEVEL: Joi.string().required(),
  DIAN_COMPANY_RESPONSIBILITY: Joi.string().required(),
  DIAN_COMPANY_PHONE: Joi.string().required(),
  DIAN_COMPANY_EMAIL: Joi.string().email().required(),
  DIAN_COMPANY_ADDRESS: Joi.string().required(),
  DIAN_COMPANY_CITY_CODE: Joi.string().required(),
  DIAN_COMPANY_CITY_NAME: Joi.string().required(),
  DIAN_COMPANY_DEPARTMENT_CODE: Joi.string().required(),
  DIAN_COMPANY_DEPARTMENT_NAME: Joi.string().required(),
  DIAN_COMPANY_COUNTRY_CODE: Joi.string().required(),
  DIAN_COMPANY_COUNTRY_NAME: Joi.string().required(),
  DIAN_COMPANY_MUNICIPALITY_CODE: Joi.string().required(),
  DIAN_RESOLUTION_NUMBER: Joi.string().required(),
  DIAN_RESOLUTION_PREFIX: Joi.string().required(),
  DIAN_RESOLUTION_FROM: Joi.number().required(),
  DIAN_RESOLUTION_TO: Joi.number().required(),
  DIAN_RESOLUTION_VALID_FROM: Joi.string().isoDate().required(),
  DIAN_RESOLUTION_VALID_TO: Joi.string().isoDate().required(),
  DIAN_TECHNICAL_KEY: Joi.string().required(),
  DIAN_QR_TEST_URL: Joi.string().uri().required(),
  DIAN_QR_PROD_URL: Joi.string().uri().required(),
  CERTIFICATE_PATH: Joi.string().required(),
  CERTIFICATE_PASSPHRASE: Joi.string().allow('').required(),
  MAIL_HOST: Joi.string().required(),
  MAIL_PORT: Joi.number().required(),
  MAIL_SECURE: Joi.string().valid('true', 'false').required(),
  MAIL_USER: Joi.string().required(),
  MAIL_PASS: Joi.string().required(),
  MAIL_FROM: Joi.string().required(),
  PDF_OUTPUT_DIR: Joi.string().when('NODE_ENV', {
    is: 'development',
    then: Joi.string().default('./tmp/pdf'),
    otherwise: Joi.string().required(),
  }),
  POS_PRINTER_WIDTH_MM: Joi.number().default(80),
  INVOICES_API_KEY: Joi.string().when('NODE_ENV', {
    is: 'development',
    then: Joi.string().default('dev-invoices-key'),
    otherwise: Joi.string().min(16).required(),
  }),
  CSV_SIGNATURE_ENABLED: Joi.string().valid('true', 'false').default('false'),
  CSV_SIGNATURE_HMAC_SECRET: Joi.string().when('CSV_SIGNATURE_ENABLED', {
    is: 'true',
    then: Joi.string().min(16).required(),
    otherwise: Joi.string().allow('').optional(),
  }),
  CSV_SIGNATURE_KEY_ID: Joi.string().default('csv-hmac-v1'),
});